### ISSUE TITLE
ignores first letter in mavlink shell

### ISSUE THREAD

**Issue by ChristophTobler** [01org/mavlink-router#108]
When I run the mavlink shell on with the Aero and run `uorb top` the output is `nsh: orb: command not found`. If I run it with a space in the beginning it works ` uorb top`.
However `param show EKF2_H*` works without the space.

**Comment by lucasdemarchi** [comment]
Can we close this?

**Comment by ChristophTobler** [comment]
Yup, I guess. I never came across this issue anymore. Otherwise, I'll reopen the issue. :+1:
