### ISSUE TITLE
Generate mavlink.h header file

### ISSUE THREAD

**Issue by RohanKurane** [01org/mavlink-router#111]
1. From home dir:
     git clone --recursive https://github.com/mavlink/mavlink.git
2. cd mavlink
3. sudo apt install python-pip
    pip2 install future
4. export PYTHONPATH=/usr/local/lib/python2.7/dist-packages:/home/rohan/mavlink
5. Run command
    rohan@penguin:~/mavlink$ python -m pymavlink.tools.mavgen
    usage: mavgen.py [-h] [-o OUTPUT]
                 [--lang {C,CS,JavaScript,Python,WLua,ObjC,Swift,Java,C++11}]
                 [--wire-protocol {0.9,1.0,2.0}] [--no-validate]
                 [--error-limit ERROR_LIMIT]
                 XML [XML ...]  
      mavgen.py: error: too few arguments

What are the steps and where are the generated files installed ?

Thanks

**Comment by zehortigoza** [comment]
This is not related to mavlink-router... but you are missing some arguments, run pymavlink/tools/mavgen.py --help but you should use something like this:

```
pymavlink/tools/mavgen.py -o generated/ --lang C --wire-protocol 2.0 message_definitions/v1.0/standard.xml
```
