### ISSUE TITLE
tcpendpoint doesn't retry on lost link

### ISSUE THREAD

**Issue by fnoop** [01org/mavlink-router#32]
Using the new tcpendpoint when connecting as a client, if the remote/server drops connection (for example if the flight controller reboots or SITL restarts) then mavlink-router loses the connection forever.
Ideally, it should retry periodically to regain the connection.

**Comment by lucasdemarchi** [comment]
A RetryTimeout value in the TcpEndpoint entry in the config file may make sense. Then we default it to 5s or so.

**Comment by edersondisouza** [comment]
@fnoop Once #34 was merged, do you believe that this issue can be closed?

**Comment by fnoop** [comment]
Confirmed fixed now, thanks :)

**Comment by fnoop** [comment]
Oh, except when it does reconnect the mavlink-routerd process goes to 100% cpu

**Comment by edersondisouza** [comment]
Almost there =D 
#57 should fix that!
Thanks for reporting!

**Comment by edersondisouza** [comment]
@fnoop is it all working well now? Can we close this issue?

**Comment by fnoop** [comment]
Yup confirmed fixed, thanks :)
