### ISSUE TITLE
Add systemd service file

### ISSUE THREAD

**Issue by edersondisouza** [01org/mavlink-router#35]

**Comment by lucasdemarchi** [comment]
@avinash-palleti for mavlink-router, please add the systemd service file in this repository. Some references on how to do it:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/Makefile.am#n44
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/configure.ac#n246
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/bluetooth.service.in  (but our type is simple, not dbus
