### ISSUE TITLE
Autodetect flight stack MAVLink dialect 

### ISSUE THREAD

**Issue by edersondisouza** [01org/mavlink-router#64]
Currently, there's a config `MavlinkDialect` to choose one of `common` (the default) and `ardupilotmega`. Add a new option `auto` and make it the default. It should detect flight stack MAVLink dialect automatically. It should be possible, as, for instance, QGroundControl is able to do that.
We could leave the option to 'force' a dialect if we see fit, or always use `auto` in the future.

**Comment by lucasdemarchi** [comment]
Fixed in #71
