### ISSUE TITLE
ulog fails when starting mavlink-router multiple times 

### ISSUE THREAD

**Issue by lucasdemarchi** [01org/mavlink-router#83]
if we try to start mavlink-router multiple times with ulog enabled, it will eventually fail saying the flight stack responded with something else than an ACK. We should deal with it rather than just fail.

**Comment by edersondisouza** [comment]
@lucasdemarchi how one could trigger this? start `mavlink-router`, close it, repeat?

**Comment by edersondisouza** [comment]
Hint - doing that didn't appear to be an issue here...

**Comment by lucasdemarchi** [comment]
I can't trigger this anymore so I'll close.
