### ISSUE TITLE
git:// url in submodules

### ISSUE THREAD

**Issue by fnoop** [01org/mavlink-router#93]
.git/modules/modules/mavlink/config contains a reference to submodule pymavlink, the url giveni s:
 ```
[submodule "pymavlink"]
	url = git://github.com/ArduPilot/pymavlink.git
```
Lots of firewalls block git://, should probably be https:// like other URLs

**Comment by anselmolsm** [comment]
pymavlink is a submodule of the MAVLink submodule. Thus, this issue should be go to MAVLink - See https://github.com/mavlink/mavlink/blob/master/.gitmodules

**Comment by fnoop** [comment]
Oops sorry!
